# Generated by Django 4.0.3 on 2022-03-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='descripton',
            new_name='description',
        ),
    ]
